//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fishing.BL.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fishing.BL.Resources.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки. Обитает на предпочтительно большой  глубине..
        /// </summary>
        internal static string ARCTICCHAR_DESCRIPTION {
            get {
                return ResourceManager.GetString("ARCTICCHAR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки.Кренки и вертушки. Обитает на предпочтительно на поверхности..
        /// </summary>
        internal static string ASP_DESCRIPTION {
            get {
                return ResourceManager.GetString("ASP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сборка не собрана!.
        /// </summary>
        internal static string ASSEMBLY_NOT_FULL {
            get {
                return ResourceManager.GetString("ASSEMBLY_NOT_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окраска у молодых - серо-серебристая, у крупных - коричневатая с золотистым отливом. Рот полунижний, небольшой, но может сильно выдвигаться, образуя длинную трубку, направленную вниз. Позади брюшных плавников киль, не покрытый чешуей, а перед спинным плавником свободная от чешуи борозда. От синца и белоглазки отличается меньшим числом ветвистых лучей в анальном плавнике и меньшим числом позвонков. Начало спинного плавника над серединой вертикали между брюшным и анальным, анальный высокий и начинается позади [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BREAM_DESCRIPTION {
            get {
                return ResourceManager.GetString("BREAM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки. Обитает на предпочтительно большой  глубине. Клюёт в основном ночью, и утром..
        /// </summary>
        internal static string BURBOT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BURBOT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки.Кренки и вертушки. Обитает на предпочтительно на поверхности. .
        /// </summary>
        internal static string CHUB_DESCRIPTION {
            get {
                return ResourceManager.GetString("CHUB_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала уберите удочку в рюкзак!.
        /// </summary>
        internal static string FIRST_UNEQUIP_ROAD {
            get {
                return ResourceManager.GetString("FIRST_UNEQUIP_ROAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки. Обитает на любой глубине..
        /// </summary>
        internal static string GRAYLING_DESCRIPTION {
            get {
                return ResourceManager.GetString("GRAYLING_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string gsg {
            get {
                return ResourceManager.GetString("gsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не назначена наживка.
        /// </summary>
        internal static string NO_BAIT_EQUIPED {
            get {
                return ResourceManager.GetString("NO_BAIT_EQUIPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указанного тэга не существует..
        /// </summary>
        internal static string NO_CURRENTTAG_FOUND {
            get {
                return ResourceManager.GetString("NO_CURRENTTAG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не назначена приманка.
        /// </summary>
        internal static string NO_LURE_EQUIPED {
            get {
                return ResourceManager.GetString("NO_LURE_EQUIPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищиник. Предпочитает мелкие и средние приманки. Обитает на любой глубине..
        /// </summary>
        internal static string PERCH_DESCRIPTION {
            get {
                return ResourceManager.GetString("PERCH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает большие и средние приманки. Обитает на любой глубине..
        /// </summary>
        internal static string PIKE_DESCRIPTION {
            get {
                return ResourceManager.GetString("PIKE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает большие и средние приманки. Обитает на предпочтительно большой глубине..
        /// </summary>
        internal static string PINKSALMON_DESCRIPTION {
            get {
                return ResourceManager.GetString("PINKSALMON_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плотва - стайная рыба. По характеру питания плотва - эврифаг. Взрослые особи питаются разнообразными беспозвоночными и их личинками, моллюсками, летом потребляют много нитчатых водорослей, а при обилии мальков крупная плотва питается личинками и мальками рыб..
        /// </summary>
        internal static string ROACH_DESCRIPTION {
            get {
                return ResourceManager.GetString("ROACH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удочка уже экипирована..
        /// </summary>
        internal static string ROAD_ALREADY_EQUIPED {
            get {
                return ResourceManager.GetString("ROAD_ALREADY_EQUIPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма тела удлиненная, но не слишком узкая, спинной плавник не длинный, высокий. Анальный плавник продолговатый, чешуя крупная, плотно сидящая. Голова вытянутая с большим носом и скошенным вниз выдвижным ртом, что говорит о донном питании рыбы. От головы до спинного плавника тянется лишенная чешуи бороздка, пространство от брюшного до анального плавника также лишено чешуи.
        ///
        ///Достигает максимальной длины в 60 сантиметров и веса до 3 килограмм (кроме подвида Малый Рыбец — до 19 сантиметров и до 100 грамм), обы [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RYBETS_DESCRIPTION {
            get {
                return ResourceManager.GetString("RYBETS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает большие и средние приманки. Обитает на предпочтительно большой глубине..
        /// </summary>
        internal static string SALMON_DESCRIPTION {
            get {
                return ResourceManager.GetString("SALMON_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тело высокое с толстой спиной, умеренно сжатое с боков. Чешуя крупная и гладкая на ощупь. Окраска варьирует в зависимости от места обитания. Золотой карась может достигать длины тела более 50 см и массы свыше 3 кг, серебряный карась — длины 40 см и массы до 2 кг..
        /// </summary>
        internal static string SILVERCARP_DESCRIPTION {
            get {
                return ResourceManager.GetString("SILVERCARP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает большие и средние приманки. Обитает на маленькой глубине..
        /// </summary>
        internal static string SNAKEHEAD_DESCRIPTION {
            get {
                return ResourceManager.GetString("SNAKEHEAD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки. Обитает на предпочтительно большой  глубине..
        /// </summary>
        internal static string TROUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("TROUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рыба сазан обладает достаточно толстым, сильным, слегка удлиненным туловищем с относительно высокой спиной и чуть уплощенными боками. Сазаны растут примерно до 8 лет, затем рост рыбы приостанавливается. Средняя длина тела сазана составляет 35-55 см, средний вес сазана достигает 1-3 кг. Гигантские экземпляры свыше 1 метра в длину и массой 20-32 кг встречаются крайне редко. По документально подтвержденным данным, самый крупный сазан был пойман во Франции в январе 2010 года на озере Лак де Кертон (Lac de Curto [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string WILDCARP_DESCRIPTION {
            get {
                return ResourceManager.GetString("WILDCARP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки. Обитает на предпочтительно большой  глубине..
        /// </summary>
        internal static string ZANDER_DESCRIPTION {
            get {
                return ResourceManager.GetString("ZANDER_DESCRIPTION", resourceCulture);
            }
        }
    }
}
